### ISSUE TITLE
Failed to install add-on v1.1.1

### ISSUE THREAD

**Issue by baylanger** [llamafilm/tesla-http-proxy-addon#1]
I had the 1st release installed w/ no issue. Tried to upgrade but it was failing w/ the error below. I also tried to uninstall / reinstall, still getting the below error.

<img width="500" alt="2024-02-07_13-17-49" src="https://github.com/llamafilm/tesla-http-proxy-addon/assets/5240348/5569f4a0-7063-40fd-88a8-655cd2ea8ca8">

Tried to pull v1.1.1 via cmd line, it's not available but 1.1.0 is still available.

```
$ docker pull ghcr.io/llamafilm/tesla_http_proxy_amd64:1.1.1
Error response from daemon: manifest unknown
```

Thank you for this work, I'm more of a devops guy if I can help in the future I'll be around. When the add-on supports other languages, I can do the French translation but it's not urgent.

[edit] I noticed there's already a translations dir. I'm a bit busy now but should be able to get that fr.yaml soon. I noticed the add-on Documentation tab uses the DOCS.md file , I'm unclear how translation would work in that case.

**Comment by llamafilm** [comment]
I made a mistake before and then fixed it with `git push --force`.  Apparently the Github action builder didn't like that, so I tried to fix it by making a benign change to the README, which made it skip the build.  I've fixed it now so that `docker pull` command works.  Please try again.
I'd be happy to accept a PR for fr.yaml but I also don't know how translation is supposed to work for the DOCS file.  Have you seen any other add-ons with working translations?

**Comment by baylanger** [comment]
git push force usually doesn't trigger a build, I faced this same issue previously.

It doesn't appear that it's possible to translate a DOCS file per the info [here](https://developers.home-assistant.io/docs/translations) . Maybe in a future hass version?!

**Comment by baylanger** [comment]
Forgot to mentioned, git pull for 1.1.1 now works... I got disturbed creating the fr.yaml file :)

Thank you!
